### ISSUE TITLE
standard style for these things

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/Top-10-FAIR#2]
We have a question about standard styles for things like links in the thing, headers levels, etc. For instance, in case of printing, do we want the link exposed so it prints.

**Comment by libcce** [comment]
That's a good point! Does pandoc help with this, otherwise, we might need to reformat the other Things. But yes, it would probably be a good thing to include the links as footnotes. Just pulled up an example in Zenodo: https://zenodo.org/record/344817#.XDzpG89KjOQ.

**Comment by libcce** [comment]
OK, looks like it is possible using pandoc -V links-as-notes

**Comment by libcce** [comment]
Hi @jt14den I couldn't get this to work last night, i.e. using pandoc to generate footnote references of all the links contained in each Thing. I think I'm going to leave this for the next version and try to publish with the links embedded in the PDF when I upload to Zenodo. The links are clickable in other PDFs I've seen on Zenodo before, so it should be fine. Writing this comment in case you want to try this today, otherwise, I'm hoping to publish to Zenodo today/tomorrow.

**Comment by libcce** [comment]
I did end up using pandoc @jt14den and it worked for the most part. I had to do some editing in MS Word.
