### ISSUE TITLE
Integrate changes from libcce/Top-10-FAIR here

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/Top-10-FAIR#7]
Before they [diverge](https://github.com/LibraryCarpentry/Top-10-FAIR/compare/master...libcce:master) too [much](https://github.com/libcce/Top-10-FAIR/compare/master...LibraryCarpentry:master).

- [x] PR @libcce's branch here
- [x] resolve merge-conflicts (locally)
- [ ] delete https://github.com/libcce/Top-10-FAIR/settings
  * re-fork from here if necessary

**Comment by orchid00** [comment]
Hi @katrinleinweber @libcce may I ask if the libcce/Top-10-FAIR is the latest version? I'm a bit confused at the moment.
BTW, The web page is looking great!

**Comment by libcce** [comment]
@katrinleinweber @orchid00 libcce/Top-10-FAIR was a place for me to test the theme that is used in LibraryCarpentry/Top-10-FAIR. Because there was some confusion, some PRs went to libcce/Top-10-FAIR, but they've also been incorporated into LibraryCarpentry/Top-10-FAIR, it's up to date. libcce/Top-10-FAIR can be deleted to avoid confusion. I'll pause to hear back, just in case there is something process-wise I'm missing but we can delete it from my side.
